import BaseSeeder from "@ioc:Adonis/Lucid/Seeder";
import Clubs from "App/Models/Clubs";
export default class extends BaseSeeder {
  public async run() {
    for (const club of rotaryClubs) {
      await Clubs.create({
        clubName: club.clubName || "pleaseReplaceThis6643643",
        clubAddress: club.clubAddress || "pleaseReplaceThis6643643",
        clubCity: club.clubCity || "pleaseReplaceThis6643643",
        clubPostal: club.clubPostal || "pleaseReplaceThis6643643",
        clubProvince: club.clubProvince || "pleaseReplaceThis6643643",
        clubCountry: "Canada",
        clubDescription:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        clubEmail: "pleaseReplaceThis6643643@gmail.com",
        districtId: 4,
        siteUrl: "",
        settings: JSON.stringify({
          disableDsg: false,
          disableDM: false,
          disableGlobal: false,
        }),
      });
    }
  }
}

const rotaryClubs = [
  {
    clubName: "1000 Islands (Brockville)",
    president: "Andrew Kizell",
    clubAddress: "Royal Canadian Legion, Branch 96",
    clubCity: "Brockville",
    clubPostal: "TBD",
    clubProvince: "ON",
    clubEmail: "TBD",
    meetingTime: "Wednesdays at 7:00 a.m.",
  },
  {
    clubName: "Alexandria Bay",
    president: "Alan Taylor",
    clubAddress: "Riveredge Resort",
    clubCity: "Alexandria Bay",
    clubPostal: "TBD",
    clubProvince: "NY",
    clubEmail: "TBD",
    meetingTime: "Wednesdays at 6:00 p.m.",
  },
  {
    clubName: "Arnprior",
    president: "Gerhard Peters",
    clubAddress: "Currently Zoom - Contact for Link",
    clubCity: "Arnprior",
    clubPostal: "TBD",
    clubProvince: "ON",
    clubEmail: "TBD",
    meetingTime: "Mondays at 7:00 p.m.",
  },
  {
    clubName: "Au Sable Valley",
    president: "Norman Jabaut",
    clubAddress: "Amos & Julia Ward Theatre",
    clubCity: "TBD",
    clubPostal: "TBD",
    clubProvince: "TBD",
    clubEmail: "TBD",
    meetingTime: "Tuesdays at 7:00 p.m.",
  },
  {
    clubName: "Barrhaven",
    president: "Colin Taylor",
    clubAddress: "Ramada Ottawa On The Rideau",
    clubCity: "Ottawa",
    clubPostal: "TBD",
    clubProvince: "ON",
    clubEmail: "TBD",
    meetingTime: "Thursdays at 7:00 p.m.",
  },
  {
    clubName: "Brockville",
    president: "Alfred O'Rourke",
    clubAddress: "Moose McGuire's Restaurant",
    clubCity: "Brockville",
    clubPostal: "TBD",
    clubProvince: "ON",
    clubEmail: "TBD",
    meetingTime: "Mondays at 12:15 p.m.",
  },
  {
    clubName: "Canton",
    president: "Timothy Welpe",
    clubAddress: "Best Western University Inn",
    clubCity: "Canton",
    clubPostal: "TBD",
    clubProvince: "NY",
    clubEmail: "TBD",
    meetingTime: "Mondays at 12:15 p.m.",
  },
  {
    clubName: "Carleton Place and Mississippi Mills",
    president: "David Cousineau",
    clubAddress: "The Final Score",
    clubCity: "Carleton Place",
    clubPostal: "TBD",
    clubProvince: "ON",
    clubEmail: "TBD",
    meetingTime: "Mondays at 6:00 p.m.",
  },
  {
    clubName: "Cataraqui-Kingston",
    president: "Bill Egnatoff",
    clubAddress: "The Spire 82 Sydenham St. & Zoom",
    clubCity: "Kingston",
    clubPostal: "TBD",
    clubProvince: "ON",
    clubEmail: "TBD",
    meetingTime: "Tuesdays at 7:00 a.m.",
  },
  {
    clubName: "Chateauguay",
    president: "George Carlisto",
    clubAddress: "Leonard's Cherry-Knoll Restaurant",
    clubCity: "Chateauguay",
    clubPostal: "TBD",
    clubProvince: "QC",
    clubEmail: "TBD",
    meetingTime: "Wednesdays at 6:15 p.m.",
  },
  {
    clubName: "Chesterville",
    president: "Dave Baerg",
    clubAddress: "Nelson Laprade Centre",
    clubCity: "Chesterville",
    clubPostal: "TBD",
    clubProvince: "ON",
    clubEmail: "TBD",
    meetingTime: "Mondays at 6:15 p.m.",
  },
  {
    clubName: "Clayton",
    president: "Christopher Mooney",
    clubAddress: "Paynter Senior Center",
    clubCity: "Clayton",
    clubPostal: "TBD",
    clubProvince: "NY",
    clubEmail: "TBD",
    meetingTime: "Tuesdays at 6:30 p.m.",
  },
  {
    clubName: "Collège Jean-de-Brébeuf",
    president: "Léa Dakessian",
    clubAddress: "Brébeuf",
    clubCity: "TBD",
    clubPostal: "TBD",
    clubProvince: "QC",
    clubEmail: "TBD",
    meetingTime: "Wednesdays at 12:15 p.m.",
  },
  {
    clubName: "Cornwall",
    president: "David Wood",
    clubAddress: "Royal Canadian Legion",
    clubCity: "Cornwall",
    clubPostal: "TBD",
    clubProvince: "ON",
    clubEmail: "TBD",
    meetingTime: "Mondays at 11:45 a.m.",
  },
  {
    clubName: "Cornwall Sunrise",
    president: "Tom Everson",
    clubAddress: "Best Western Parkway Inn & Conference Centre",
    clubCity: "Cornwall",
    clubPostal: "TBD",
    clubProvince: "ON",
    clubEmail: "TBD",
    meetingTime: "Wednesdays at 7:00 a.m.",
  },
  {
    clubName: "d7040 Passport",
    president: "Christopher Thompson",
    clubAddress: "Internet",
    clubCity: "TBD",
    clubPostal: "TBD",
    clubProvince: "TBD",
    clubEmail: "TBD",
    meetingTime: "Tuesdays at 12:00 p.m.",
  },
  {
    clubName: "E-club Premier 7040",
    president: "Anne Laure Damhet",
    clubAddress: "https://meet.goto.com/EclubPremier7040",
    clubCity: "TBD",
    clubPostal: "TBD",
    clubProvince: "TBD",
    clubEmail: "TBD",
    meetingTime: "Thursdays at 7:00 a.m.",
  },
  {
    clubName: "East of Montreal",
    president: "Plamen Minchev",
    clubAddress: "Bistro Sofia",
    clubCity: "Montreal",
    clubPostal: "TBD",
    clubProvince: "QC",
    clubEmail: "TBD",
    meetingTime: "Tuesdays at 6:30 p.m.",
  },
  {
    clubName: "Eganville",
    president: "Maria Robinson",
    clubAddress: "Eganville & District Senior Needs/Fairfields",
    clubCity: "Eganville",
    clubPostal: "TBD",
    clubProvince: "ON",
    clubEmail: "TBD",
    meetingTime: "Thursdays at 6:30 p.m.",
  },
  {
    clubName: "Gananoque",
    president: "Bern Hudson",
    clubAddress: "Gananoque Curling Club & Zoom",
    clubCity: "Gananoque",
    clubPostal: "TBD",
    clubProvince: "ON",
    clubEmail: "TBD",
    meetingTime: "Wednesdays at 5:30 p.m.",
  },
  {
    clubName: "Hawkesbury",
    president: "Walter Kasper",
    clubAddress: "Le Vieux Château Restaurant",
    clubCity: "Hawkesbury",
    clubPostal: "TBD",
    clubProvince: "ON",
    clubEmail: "TBD",
    meetingTime: "Tuesdays at 6:00 p.m.",
  },
  {
    clubName: "Hull",
    president: "Pierre Charlebois",
    clubAddress: "Restaurant Pacini",
    clubCity: "Hull",
    clubPostal: "TBD",
    clubProvince: "QC",
    clubEmail: "TBD",
    meetingTime: "Thursdays at 12:30 p.m.",
  },
  {
    clubName: "Iqaluit",
    president: "Adam Fisher",
    clubAddress: "Royal Canadian Legion's Quiet Lounge.",
    clubCity: "Iqaluit",
    clubPostal: "TBD",
    clubProvince: "NU",
    clubEmail: "TBD",
    meetingTime: "Wednesdays at 12:00 p.m.",
  },
  {
    clubName: "John Abbott",
    president: "Anisa Hashemi",
    clubAddress: "Location",
    clubCity: "TBD",
    clubPostal: "TBD",
    clubProvince: "TBD",
    clubEmail: "TBD",
    meetingTime: "Tuesdays at 5:30 p.m.",
  },
  {
    clubName: "Kanata Rotary Club",
    president: "Ruth Hawkins",
    clubAddress: "Royal Canadian Legion",
    clubCity: "Kanata",
    clubPostal: "TBD",
    clubProvince: "ON",
    clubEmail: "TBD",
    meetingTime: "Wednesdays at 7:00 a.m.",
  },
  {
    clubName: "Kemptville",
    president: "Bruce Wehlau",
    clubAddress: "Grenville Mutual Insurance Building (Community Room)",
    clubCity: "Kemptville",
    clubPostal: "TBD",
    clubProvince: "ON",
    clubEmail: "TBD",
    meetingTime: "Tuesdays at 6:30 p.m.",
  },
  {
    clubName: "Kingston",
    president: "Don Heath",
    clubAddress: "Kingsbridge Retirement Community",
    clubCity: "Kingston",
    clubPostal: "TBD",
    clubProvince: "ON",
    clubEmail: "TBD",
    meetingTime: "Thursdays at 12:15 p.m.",
  },
  {
    clubName: "Kingston",
    president: "Aaliyah Strachan",
    clubAddress: "Seaway Coworking",
    clubCity: "Kingston",
    clubPostal: "TBD",
    clubProvince: "ON",
    clubEmail: "TBD",
    meetingTime: "Thursdays at 6:30 p.m.",
  },
  {
    clubName: "Kingston Waterfront",
    president: "Martha Hatt",
    clubAddress: "RCHA",
    clubCity: "Kingston",
    clubPostal: "TBD",
    clubProvince: "ON",
    clubEmail: "TBD",
    meetingTime: "Mondays at 5:30 p.m.",
  },
  {
    clubName: "Kingston-Frontenac",
    president: "Arja Hamalainen",
    clubAddress: "BW Fireside Inn (Bistro Stefan)",
    clubCity: "Kingston",
    clubPostal: "TBD",
    clubProvince: "ON",
    clubEmail: "TBD",
    meetingTime: "Wednesdays at 6:15 p.m.",
  },
  {
    clubName: "L'île de Montréal",
    president: "Starlithe Violetta Blaise",
    clubAddress: "Alfid",
    clubCity: "Montréal",
    clubPostal: "TBD",
    clubProvince: "QC",
    clubEmail: "TBD",
    meetingTime: "Wednesdays at 6:30 p.m.",
  },
  {
    clubName: "Lake Placid",
    president: "Kathleen Thompson",
    clubAddress: "Hampton Inn & Suites",
    clubCity: "Lake Placid",
    clubPostal: "TBD",
    clubProvince: "NY",
    clubEmail: "TBD",
    meetingTime: "Thursdays at 7:20 a.m.",
  },
  {
    clubName: "Laval Rive-Nord",
    president: "Sonia Cantalupi",
    clubAddress: "Microbrasserie Noire et Blanche",
    clubCity: "Laval",
    clubPostal: "TBD",
    clubProvince: "QC",
    clubEmail: "TBD",
    meetingTime: "Wednesdays at 6:30 p.m.",
  },
  {
    clubName: "Malone",
    president: "Nancy Montevago",
    clubAddress: "Malone Golf Club",
    clubCity: "Malone",
    clubPostal: "TBD",
    clubProvince: "NY",
    clubEmail: "TBD",
    meetingTime: "Thursdays at 12:00 p.m.",
  },
  {
    clubName: "Massena",
    president: "Nicholas White",
    clubAddress: "Morley's",
    clubCity: "Massena",
    clubPostal: "TBD",
    clubProvince: "NY",
    clubEmail: "TBD",
    meetingTime: "Tuesdays at 12:00 p.m.",
  },
  {
    clubName: "Metro Montreal",
    president: "Mark Pedicelli",
    clubAddress: "Wunder Bar",
    clubCity: "Montreal",
    clubPostal: "TBD",
    clubProvince: "QC",
    clubEmail: "TBD",
    meetingTime: "Sundays",
  },
  {
    clubName: "Mont-Tremblant",
    president: "Mark Pedicelli",
    clubAddress: "Location",
    clubCity: "Mont-Tremblant",
    clubPostal: "TBD",
    clubProvince: "QC",
    clubEmail: "TBD",
    meetingTime: "Thursdays at 7:30 a.m.",
  },
  {
    clubName: "Montreal Cedars",
    president: "Maha Maalouf-Kassouf",
    clubAddress: "Online",
    clubCity: "Montreal",
    clubPostal: "TBD",
    clubProvince: "QC",
    clubEmail: "TBD",
    meetingTime: "Mondays at 8:00 p.m.",
  },
  {
    clubName: "Ottawa",
    president: "Maria Khan",
    clubAddress: "Jack Purcell Centre and online",
    clubCity: "Ottawa",
    clubPostal: "TBD",
    clubProvince: "ON",
    clubEmail: "TBD",
    meetingTime: "Mondays at 12:15 p.m.",
  },
  {
    clubName: "Ottawa Bytown",
    president: "Mike Morris",
    clubAddress: "P.O. Box 4601",
    clubCity: "Ottawa",
    clubPostal: "TBD",
    clubProvince: "ON",
    clubEmail: "TBD",
    meetingTime: "Tuesdays at 7:15 a.m.",
  },
  {
    clubName: "Ottawa Metro",
    president: "Christa Reccord",
    clubAddress: "Montgomery Legion (home meeting location)",
    clubCity: "Ottawa",
    clubPostal: "TBD",
    clubProvince: "ON",
    clubEmail: "TBD",
    meetingTime: "Mondays at 5:45 p.m.",
  },
  {
    clubName: "Ottawa South",
    president: "Rosemary Parker",
    clubAddress: "Hybrid (in-person and online)",
    clubCity: "Ottawa",
    clubPostal: "TBD",
    clubProvince: "ON",
    clubEmail: "TBD",
    meetingTime: "Wednesdays at 12:30 p.m.",
  },
  {
    clubName: "Ottawa-Stittsville",
    president: "Annette Lindsay",
    clubAddress: "Stittsville United Church",
    clubCity: "Ottawa",
    clubPostal: "TBD",
    clubProvince: "ON",
    clubEmail: "TBD",
    meetingTime: "Wednesdays at 7:00 a.m.",
  },
  {
    clubName: "Pembroke",
    president: "Dave Foohey",
    clubAddress: "Finnigan's Restaurant",
    clubCity: "Pembroke",
    clubPostal: "TBD",
    clubProvince: "ON",
    clubEmail: "TBD",
    meetingTime: "Tuesdays at 8:00 a.m.",
  },
  {
    clubName: "Petawawa Rotary",
    president: "Scott Randolph",
    clubAddress: "Rotary Room Petawawa Civic Center",
    clubCity: "Petawawa",
    clubPostal: "TBD",
    clubProvince: "ON",
    clubEmail: "TBD",
    meetingTime: "Tuesdays at 6:00 p.m.",
  },
  {
    clubName: "Plattsburgh",
    president: "Edward Kirby",
    clubAddress: "MHAB Life Skills Campus, Dining Hall",
    clubCity: "Plattsburgh",
    clubPostal: "TBD",
    clubProvince: "NY",
    clubEmail: "TBD",
    meetingTime: "Wednesdays at 12:00 p.m.",
  },
  {
    clubName: "Plattsburgh Sunrise",
    president: "Sue LeBlanc-Durocher",
    clubAddress: "SUNY Plattsburgh Au Sable Hall",
    clubCity: "Plattsburgh",
    clubPostal: "TBD",
    clubProvince: "NY",
    clubEmail: "TBD",
    meetingTime: "Tuesdays at 7:30 a.m.",
  },
  {
    clubName: "Potsdam",
    president: "Sunday Smith",
    clubAddress: "Potsdam Town Hall Community Room",
    clubCity: "Potsdam",
    clubPostal: "TBD",
    clubProvince: "NY",
    clubEmail: "TBD",
    meetingTime: "Wednesdays at 12:00 p.m.",
  },
  {
    clubName: "Queen's University",
    president: "Thomas Huo",
    clubAddress: "Queen's University Mac-Corry Hall E229",
    clubCity: "Kingston",
    clubPostal: "TBD",
    clubProvince: "ON",
    clubEmail: "TBD",
    meetingTime: "Thursdays at 5:30 p.m.",
  },
  {
    clubName: "Renfrew",
    president: "Christine Jarrett",
    clubAddress: "RCAF Wing",
    clubCity: "Renfrew",
    clubPostal: "TBD",
    clubProvince: "ON",
    clubEmail: "TBD",
    meetingTime: "Tuesdays at 12:10 p.m.",
  },
  {
    clubName: "Saranac Lake",
    president: "Jasen Lawrence",
    clubAddress: "St. Luke's Parish Hall",
    clubCity: "Saranac Lake",
    clubPostal: "TBD",
    clubProvince: "NY",
    clubEmail: "TBD",
    meetingTime: "Tuesdays at 7:30 a.m.",
  },
  {
    clubName: "Shawville",
    president: "Susan Page",
    clubAddress: "Cafe 349",
    clubCity: "Shawville",
    clubPostal: "TBD",
    clubProvince: "QC",
    clubEmail: "TBD",
    meetingTime: "Mondays at 5:30 p.m.",
  },
  {
    clubName: "Smiths Falls",
    president: "Stewart Blair",
    clubAddress: "Hawks Nest Cafe",
    clubCity: "Smiths Falls",
    clubPostal: "TBD",
    clubProvince: "ON",
    clubEmail: "TBD",
    meetingTime: "Wednesdays at 7:30 a.m.",
  },
  {
    clubName: "St. Jerome",
    president: "Mario Cornellier",
    clubAddress: "Zoom Meeting seulement",
    clubCity: "St. Jerome",
    clubPostal: "TBD",
    clubProvince: "QC",
    clubEmail: "TBD",
    meetingTime: "Mondays at 6:00 p.m.",
  },
  {
    clubName: "SUNY Plattsburgh",
    president: "Amy Imanguingo",
    clubAddress: "Winkel Sculpture Gallery",
    clubCity: "Plattsburgh",
    clubPostal: "TBD",
    clubProvince: "NY",
    clubEmail: "TBD",
    meetingTime: "Wednesdays at 5:00 p.m.",
  },
  {
    clubName: "Tupper Lake",
    president: "Rickey Dattola",
    clubAddress: "Tupper Lake Golf Club",
    clubCity: "Tupper Lake",
    clubPostal: "TBD",
    clubProvince: "NY",
    clubEmail: "TBD",
    meetingTime: "Wednesdays at 6:00 p.m.",
  },
  {
    clubName: "Valleyfield",
    president: "Sandrine Vinet",
    clubAddress: "DEZ Taverne Urbaine",
    clubCity: "Valleyfield",
    clubPostal: "TBD",
    clubProvince: "QC",
    clubEmail: "TBD",
    meetingTime: "Tuesdays at 12:15 p.m.",
  },
  {
    clubName: "Watertown",
    president: "Tom Deuson",
    clubAddress: "Italian American Civic Assoc",
    clubCity: "Watertown",
    clubPostal: "TBD",
    clubProvince: "NY",
    clubEmail: "TBD",
    meetingTime: "Wednesdays at 12:00 p.m.",
  },
  {
    clubName: "Watertown Sunrise",
    president: "Patrick Signor",
    clubAddress: "Hilton Garden Inn",
    clubCity: "Watertown",
    clubPostal: "TBD",
    clubProvince: "NY",
    clubEmail: "TBD",
    meetingTime: "Thursdays at 7:30 a.m.",
  },
  {
    clubName: "West Ottawa",
    president: "Patrick Armstrong",
    clubAddress: "Nepean Sailing Club",
    clubCity: "Ottawa",
    clubPostal: "TBD",
    clubProvince: "ON",
    clubEmail: "TBD",
    meetingTime: "Mondays at 12:15 p.m.",
  },
  {
    clubName: "Westmount",
    president: "Tony Layton",
    clubAddress: "Victoria Hall",
    clubCity: "Westmount",
    clubPostal: "TBD",
    clubProvince: "QC",
    clubEmail: "TBD",
    meetingTime: "Wednesdays at 12:00 p.m.",
  },
];
