on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        touch ~/.ssh/known_hosts
        echo "${{ secrets.SSH_KEY }}" > id_rsa
        chmod 600 id_rsa
        ssh-keyscan -t rsa ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

    - name: Deploy Rotary
      run: |
        ssh -i id_rsa ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }} <<'ENDSSH'
          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S sh -c '
          cd /home/appadmin/TestMyRotaryProject/myrotary-projects
          # Stash and pull latest code
          git stash
          git pull
          cd backend
          BUILD_DIR="/home/appadmin/TestMyRotaryProject/myrotary-projects/backend/build"
          if [ -d "$BUILD_DIR" ]; then
            rm -r "$BUILD_DIR"
          fi
          npm install
          node ace build --production --ignore-ts-errors
          # Copy environment file to build directory
          cp /home/appadmin/testfiles/.env /home/appadmin/TestMyRotaryProject/myrotary-projects/backend/build
          
          # Navigate to build directory and install production dependencies
          cd build
          ls -al
          npm ci --production
          
          # Manage PM2 processes
          pm2 delete all
          pm2 save --force
          pm2 start /home/appadmin/TestMyRotaryProject/myrotary-projects/backend/build/server.js -i -f --name TestApi
          pm2 save
          pm2 list
          
          # Frontend Deployment
          cd /home/appadmin/TestMyRotaryProject/myrotary-projects/frontend
          npm install
          chmod -R a+x node_modules
          npm run build-only
          
          # Remove existing frontend build directory if it exists
          cd /var/www/test
          BUILD_DIR="/var/www/test/dist"
          if [ -d "$BUILD_DIR" ]; then
            sudo rm -r "$BUILD_DIR"
          fi
          
          # Move new frontend build to web directory
          mv /home/appadmin/TestMyRotaryProject/myrotary-projects/frontend/dist /var/www/test
          # Add more sudo commands here if needed
          '
        ENDSSH
